version: 2
updates:
  # Flutter dependencies
  - package-ecosystem: "pub"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "juanvallejo97"
    labels:
      - "dependencies"
      - "flutter"
    commit-message:
      prefix: "deps"
      include: "scope"
  
  # Cloud Functions dependencies
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "juanvallejo97"
    labels:
      - "dependencies"
      - "functions"
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: increase
  
  # WebApp dependencies
  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "juanvallejo97"
    labels:
      - "dependencies"
      - "webapp"
    commit-message:
      prefix: "deps"
      include: "scope"
    versioning-strategy: increase
  
  # Firestore tests dependencies
  - package-ecosystem: "npm"
    directory: "/firestore-tests"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "juanvallejo97"
    labels:
      - "dependencies"
      - "tests"
    commit-message:
      prefix: "deps"
      include: "scope"
  
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    reviewers:
      - "juanvallejo97"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
