version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule: { interval: "monthly" }
  - package-ecosystem: "npm"
    directory: "/functions"
    schedule: { interval: "weekly" }
  - package-ecosystem: "npm"
    directory: "/firestore-tests"
    schedule: { interval: "weekly" }
  - package-ecosystem: "pub"
    directory: "/"
    schedule: { interval: "weekly" }
