- name: bug
  color: d73a4a
  description: Something isn't working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: chore
  color: cfd3d7
  description: Build, tooling, or maintenance tasks
- name: test
  color: e4e669
  description: Adding or updating tests
- name: ci
  color: 0e8a16
  description: Continuous Integration
- name: priority:high
  color: b60205
  description: Must be addressed as soon as possible
- name: priority:medium
  color: fbca04
  description: Important but not urgent
- name: priority:low
  color: 0e8a16
  description: Nice to have
- name: status:blocked
  color: 5319e7
  description: Blocked by another task or issue
- name: status:needs-info
  color: 5319e7
  description: More information required
- name: size:S
  color: 6f42c1
  description: Small change
- name: size:M
  color: 6f42c1
  description: Medium change
- name: size:L
  color: 6f42c1
  description: Large change
- name: area:frontend
  color: 1d76db
  description: Flutter app changes
- name: area:backend
  color: 0052cc
  description: Cloud Functions or rules
- name: area:docs
  color: 0366d6
  description: Documentation changes
