include: package:flutter_lints/flutter.yaml
linter:
  rules:
    avoid_print: true
    unawaited_futures: true
    always_declare_return_types: true
    prefer_const_constructors: true
    prefer_single_quotes: true
analyzer:
  exclude:
    - build/**
    - ios/**
    - android/**
    - web/**
