dependencies:
  firebase_core: ^4.1.1
  firebase_auth: ^6.2.0
  firebase_storage: ^13.3.1
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2
  firebase_app_check: ^0.4.1
  firebase_performance: ^0.10.1+10
  firebase_crashlytics: ^4.1.3
  firebase_analytics: ^11.3.3
  firebase_remote_config: ^6.0.2
  # other dependencies...
