name: sierra_painting
description: Professional painting services management application
publish_to: "none"
version: 0.0.12+12

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_dotenv: ^5.1.0
  json_annotation: ^4.9.0

  # Firebase
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  firebase_storage: ^13.0.2
  cloud_firestore: ^6.0.2
  cloud_functions: ^6.0.2
  firebase_app_check: ^0.4.1
  firebase_remote_config: ^6.0.2
  firebase_crashlytics: ^5.0.2
  firebase_performance: ^0.11.1
  firebase_analytics: ^12.0.0

  # State Management
  flutter_riverpod: ^3.0.2
  provider: ^6.1.5

  # Routing
  go_router: ^16.2.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5

  # UI/UX
  intl: ^0.20.2
  cached_network_image: ^3.4.1

  # Networking
  http: ^1.5.0
  connectivity_plus: ^7.0.0

  # Payments
  flutter_stripe: ^12.0.2

  # Utilities
  uuid: ^4.5.1
  google_fonts: ^6.3.2
  import_sorter: ^4.6.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  fake_cloud_firestore: 4.0.0

  firebase_core_platform_interface: ^6.0.1

  # Code Generation
  build_runner: ^2.5.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4

  # Code Quality
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # SECURITY: Do NOT add .env to assets - it bundles secrets into the app!
    # Use flutter_dotenv.load() which reads from filesystem instead
    - assets/config/public.env
    - assets/images/
    - assets/icons/

  # fonts:
  #   - family: Custom
  #     fonts:
  #       - asset: fonts/Custom-Regular.ttf
