name: PR Labels
on:
  pull_request_target:
    types: [opened, synchronize, reopened, edited]
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
  size:
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/size-label-action@v0.5.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IGNORED: "package-lock.json yarn.lock pnpm-lock.yaml pubspec.lock .dart_tool/** node_modules/**"