// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiveErLn0w7ojBMQOCVak-0m897XRqvsk',
    appId: '1:271985878317:web:554db8ba14a801be589fa4',
    messagingSenderId: '271985878317',
    projectId: 'sierra-painting-staging',
    authDomain: 'sierra-painting-staging.firebaseapp.com',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoMH7_Z7ele3Dlg4TeHPHHRNtxKUuYAY',
    appId: '1:271985878317:android:b3b71b78fd6185fe589fa4',
    messagingSenderId: '271985878317',
    projectId: 'sierra-painting-staging',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrYFn2HaePfewi5bN5OFpVBlMfypzTmik',
    appId: '1:271985878317:ios:a18310fce2d98878589fa4',
    messagingSenderId: '271985878317',
    projectId: 'sierra-painting-staging',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
    iosBundleId: 'com.example.sierraPainting',
  );
}
