// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJizvq82-zsud2NLtp_AtiboIV7mn2WOs',
    appId: '1:138777646966:web:4d2b7855b2cb2b0c7e0c57',
    messagingSenderId: '138777646966',
    projectId: 'to-do-app-ac602',
    authDomain: 'to-do-app-ac602.firebaseapp.com',
    storageBucket: 'to-do-app-ac602.firebasestorage.app',
    measurementId: 'G-G5JY0MJZMH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBqKtYuqDTcv7uwRLShoCt7b2sPWm_Uks',
    appId: '1:138777646966:android:36104ede7ac939a87e0c57',
    messagingSenderId: '138777646966',
    projectId: 'to-do-app-ac602',
    storageBucket: 'to-do-app-ac602.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe_2n0gBPDZiOdwYvq-3r-jsqWyZ_V6g',
    appId: '1:138777646966:ios:eb8f44789bae81f27e0c57',
    messagingSenderId: '138777646966',
    projectId: 'to-do-app-ac602',
    storageBucket: 'to-do-app-ac602.firebasestorage.app',
    iosBundleId: 'com.example.sierraPainting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'sierra-painting',
    storageBucket: 'sierra-painting.appspot.com',
    iosBundleId: 'com.sierrapainting.app',
  );
}
