// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiveErLn0w7ojBMQOCVak-0m897XRqvsk',
    appId: '1:271985878317:web:554db8ba14a801be589fa4',
    messagingSenderId: '271985878317',
    projectId: 'sierra-painting-staging',
    authDomain: 'sierra-painting-staging.firebaseapp.com',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZoMH7_Z7ele3Dlg4TeHPHHRNtxKUuYAY',
    appId: '1:271985878317:android:b3b71b78fd6185fe589fa4',
    messagingSenderId: '271985878317',
    projectId: 'sierra-painting-staging',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNe_2n0gBPDZiOdwYvq-3r-jsqWyZ_V6g',
    appId: '1:138777646966:ios:eb8f44789bae81f27e0c57',
    messagingSenderId: '138777646966',
    projectId: 'sierra-painting-staging',
    storageBucket: 'sierra-painting-staging.firebasestorage.app',
    iosBundleId: 'com.sierrapainting.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'sierra-painting',
    storageBucket: 'sierra-painting.appspot.com',
    iosBundleId: 'com.sierrapainting.app',
  );
}
