name: Deploy to Staging

on:
  push:
    branches: [ main ]

jobs:
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Install Functions dependencies
        working-directory: ./functions
        run: npm ci
      
      - name: Build Functions
        working-directory: ./functions
        run: npm run build
      
      - name: Deploy to Firebase Staging
        run: firebase deploy --only functions,firestore:rules,storage:rules --project staging
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
