---
name: Security - Firestore Rules

on:
  pull_request:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'firestore-tests/**'
      - '.github/workflows/firestore_rules.yml'
  push:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'firestore-tests/**'

jobs:
  rules:
    name: rules
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'

      - name: Setup Java (for Firebase Emulator)
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install test dependencies
        working-directory: firestore-tests
        run: |
          npm ci --prefer-offline --no-audit || \
            npm install --no-audit --no-fund
        shell: bash

      - name: Start Firebase Emulator and Run Tests
        working-directory: firestore-tests
        run: |
          # Start emulator in background
          firebase emulators:start --only firestore --project demo-test &
          EMULATOR_PID=$!

          # Wait for emulator to be ready
          echo "Waiting for emulator to start..."
          sleep 10

          # Run tests
          npm test || TEST_RESULT=$?

          # Stop emulator
          kill $EMULATOR_PID || true

          # Exit with test result
          exit ${TEST_RESULT:-0}
        shell: bash
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
