---
name: Flutter CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  analyze-and-test-flutter:
    name: Analyze and Test Flutter
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '17'

      - name: Install dependencies
        run: flutter pub get
        shell: bash

      - name: Analyze
        run: flutter analyze
        shell: bash

      - name: Run tests with coverage
        run: flutter test --coverage
        shell: bash

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: |
            gradle-${{ runner.os }}-${{ hashFiles(
              '**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Build APK (debug)
        run: flutter build apk --debug
        shell: bash
