name: Security - Prevent JSON Credentials

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  check-for-json-service-account-keys:
    name: Check for JSON Service Account Keys
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Check for GOOGLE_APPLICATION_CREDENTIALS usage
        run: |
          echo "🔍 Checking for prohibited GOOGLE_APPLICATION_CREDENTIALS usage..."
          
          # Check for GOOGLE_APPLICATION_CREDENTIALS environment variable
          if grep -r "GOOGLE_APPLICATION_CREDENTIALS" .github/workflows/ 2>/dev/null | grep -v "# Allow"; then
            echo "❌ FAILED: Found GOOGLE_APPLICATION_CREDENTIALS in workflows!"
            echo ""
            echo "POLICY VIOLATION: Using GOOGLE_APPLICATION_CREDENTIALS with JSON keys is prohibited."
            echo "Use Workload Identity Federation with 'workload_identity_provider' instead."
            echo ""
            echo "See: docs/ops/gcp-workload-identity-setup.md"
            exit 1
          fi
          
          echo "✅ No GOOGLE_APPLICATION_CREDENTIALS found in workflows"
      
      - name: Check for credentials_json in workflows
        run: |
          echo "🔍 Checking for credentials_json parameter in workflows..."
          
          # Check for credentials_json in google-github-actions/auth
          if grep -r "credentials_json:" .github/workflows/ 2>/dev/null; then
            echo "❌ FAILED: Found credentials_json in workflows!"
            echo ""
            echo "POLICY VIOLATION: Using credentials_json with service account keys is prohibited."
            echo "Use Workload Identity Federation with 'workload_identity_provider' instead."
            echo ""
            echo "Required changes:"
            echo "  - Remove: credentials_json: \${{ secrets.FIREBASE_SERVICE_ACCOUNT }}"
            echo "  - Add: workload_identity_provider: \${{ vars.GCP_WORKLOAD_IDENTITY_PROVIDER }}"
            echo "  - Add: service_account: \${{ vars.GCP_SERVICE_ACCOUNT }}"
            echo "  - Add permissions block: permissions: { contents: read, id-token: write }"
            echo ""
            echo "See: docs/ops/gcp-workload-identity-setup.md"
            exit 1
          fi
          
          echo "✅ No credentials_json found in workflows"
      
      - name: Check for service account JSON files
        run: |
          echo "🔍 Checking for service account JSON files in repository..."
          
          # Patterns that indicate GCP service account JSON keys
          FOUND=0
          
          # Check for files with service account patterns (excluding this workflow and docs)
          if find . -type f -name "*.json" ! -path "./.git/*" ! -path "./node_modules/*" ! -path "./build/*" -exec grep -l "private_key" {} \; 2>/dev/null | grep -v ".github/workflows/prevent-json-credentials.yml"; then
            echo "⚠️  WARNING: Found JSON files containing private_key field!"
            echo "This may indicate a service account key file."
            FOUND=1
          fi
          
          # Check for common service account key filenames
          if find . -type f \( -name "*service-account*.json" -o -name "*credentials*.json" -o -name "*serviceAccountKey*.json" \) ! -path "./.git/*" ! -path "./node_modules/*" 2>/dev/null | head -n 1; then
            echo "⚠️  WARNING: Found files with service account naming patterns!"
            FOUND=1
          fi
          
          if [ $FOUND -eq 1 ]; then
            echo ""
            echo "❌ POLICY VIOLATION: Service account JSON keys should not be committed to the repository."
            echo ""
            echo "If this is a false positive, update this workflow to exclude the file."
            echo "If this is a real key file, remove it immediately:"
            echo "  1. git rm <file>"
            echo "  2. git commit -m 'Remove service account key'"
            echo "  3. Revoke the key in GCP Console"
            echo "  4. Use Workload Identity Federation instead"
            echo ""
            exit 1
          fi
          
          echo "✅ No service account JSON files found"
      
      - name: Verify Workload Identity usage
        run: |
          echo "🔍 Verifying Workload Identity Federation is used..."
          
          # Check that workflows use workload_identity_provider
          WIF_COUNT=$(grep -r "workload_identity_provider:" .github/workflows/ 2>/dev/null | wc -l)
          
          if [ "$WIF_COUNT" -eq 0 ]; then
            echo "⚠️  WARNING: No Workload Identity Federation configuration found!"
            echo ""
            echo "Expected to find 'workload_identity_provider' in deployment workflows."
            echo "See: docs/ops/gcp-workload-identity-setup.md"
          else
            echo "✅ Found $WIF_COUNT Workload Identity Federation configuration(s)"
          fi
          
          # Check for required permissions block
          PERMS_COUNT=$(grep -A 2 "permissions:" .github/workflows/ 2>/dev/null | grep "id-token: write" | wc -l)
          
          if [ "$PERMS_COUNT" -eq 0 ]; then
            echo "⚠️  WARNING: No 'id-token: write' permission found!"
            echo ""
            echo "Workload Identity Federation requires:"
            echo "  permissions:"
            echo "    contents: read"
            echo "    id-token: write"
          else
            echo "✅ Found $PERMS_COUNT job(s) with correct OIDC permissions"
          fi
      
      - name: Policy summary
        run: |
          echo ""
          echo "=========================================="
          echo "📋 Security Policy Check Summary"
          echo "=========================================="
          echo ""
          echo "✅ All security policy checks passed"
          echo ""
          echo "Security requirements:"
          echo "  ✓ No GOOGLE_APPLICATION_CREDENTIALS usage"
          echo "  ✓ No credentials_json in workflows"
          echo "  ✓ No service account JSON keys committed"
          echo "  ✓ Workload Identity Federation enforced"
          echo ""
          echo "For more information:"
          echo "  - Workload Identity Setup: docs/ops/gcp-workload-identity-setup.md"
          echo "  - GitHub Environments: docs/ops/github-environments.md"
          echo "  - Security Guide: docs/Security.md"
          echo ""
