name: Release V1 (Manual)
on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to create (e.g., v1.0.0)"
        required: true
permissions:
  contents: write
  id-token: write
env:
  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
  FIREBASE_HOSTING_SITE: ${{ secrets.FIREBASE_HOSTING_SITE }}
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get && flutter build web --release
      - name: Create tag
        run: |
          git config user.name "github-actions"
          git config user.email "actions@users.noreply.github.com"
          git tag "${{ github.event.inputs.tag }}"
          git push origin "${{ github.event.inputs.tag }}"
      - name: Install firebase-tools
        run: npm i -g firebase-tools
      - name: Ensure Hosting site
        run: firebase hosting:sites:create "$FIREBASE_HOSTING_SITE" --project "$FIREBASE_PROJECT_ID" || true
      - name: Deploy (explicit flags)
        run: firebase deploy --only hosting --project "$FIREBASE_PROJECT_ID" --site "$FIREBASE_HOSTING_SITE" --non-interactive --force
