name: Firestore Rules Tests

on:
  pull_request:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'functions/src/test/rules.test.ts'
      - '.github/workflows/rules-test.yml'
  push:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'functions/src/test/rules.test.ts'

jobs:
  test-rules:
    name: Test Firestore Security Rules
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json
      
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Install functions dependencies
        working-directory: functions
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi
      
      - name: Start Firebase Emulators
        working-directory: functions
        run: |
          # Start emulators in background
          firebase emulators:start --only firestore --project sierra-painting-test &
          EMULATOR_PID=$!
          echo "EMULATOR_PID=$EMULATOR_PID" >> $GITHUB_ENV
          
          # Wait for emulator to be ready (max 30 seconds)
          echo "Waiting for Firestore emulator to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null 2>&1; then
              echo "Firestore emulator is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 1
          done
          
          # Verify emulator is running
          if ! curl -s http://localhost:8080 > /dev/null 2>&1; then
            echo "ERROR: Firestore emulator failed to start"
            exit 1
          fi
      
      - name: Run rules tests
        working-directory: functions
        run: npm run test:rules
      
      - name: Stop Firebase Emulators
        if: always()
        run: |
          if [ ! -z "$EMULATOR_PID" ]; then
            kill $EMULATOR_PID || true
          fi
          # Kill any remaining emulator processes
          pkill -f "firebase.*emulator" || true
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: rules-test-results
          path: |
            functions/coverage/
            functions/junit.xml
          if-no-files-found: ignore
      
      - name: Comment PR with results
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v7
        with:
          script: |
            const body = `## ❌ Firestore Rules Tests Failed
            
            The security rules tests have failed. Please review the logs and fix any issues before merging.
            
            **Action Required:**
            - Review the test failures in the workflow logs
            - Update \`firestore.rules\` or tests as needed
            - Ensure all security validations pass
            
            See the [workflow run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            });
