name: Security - Firestore Rules

on:
  pull_request:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'firestore-tests/**'
      - '.github/workflows/rules-test.yml'
  push:
    branches: [main]
    paths:
      - 'firestore.rules'
      - 'firestore-tests/**'

jobs:
  rules:
    name: rules
    runs-on: ubuntu-latest
    
    services:
      firestore:
        image: google/cloud-sdk:emulators
        ports:
          - 8080:8080
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      
      - name: Start Firestore Emulator in background
        run: |
          # Start emulator in the background
          gcloud emulators firestore start --host-port=0.0.0.0:8080 &
          EMULATOR_PID=$!
          echo "EMULATOR_PID=$EMULATOR_PID" >> $GITHUB_ENV
          
          # Wait for emulator to be ready (max 30 seconds)
          echo "Waiting for Firestore emulator to start..."
          for i in {1..30}; do
            if curl -s http://localhost:8080 > /dev/null 2>&1; then
              echo "✅ Firestore emulator is ready!"
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 1
          done
          
          # Verify emulator is running
          if ! curl -s http://localhost:8080 > /dev/null 2>&1; then
            echo "❌ ERROR: Firestore emulator failed to start"
            exit 1
          fi
        timeout-minutes: 2
      
      - name: Install dependencies
        working-directory: firestore-tests
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install --no-audit --no-fund
          fi
      
      - name: Run Firestore Rules tests
        working-directory: firestore-tests
        run: npm test
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
      
      - name: Stop Firestore Emulator
        if: always()
        run: |
          if [ ! -z "$EMULATOR_PID" ]; then
            kill $EMULATOR_PID || true
          fi
          # Kill any remaining emulator processes
          pkill -f "firestore.*emulator" || true
          pkill -f "gcloud.*emulator" || true
