name: tests
on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  widget-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter pub get
      - name: Run widget tests (no Firebase)
        run: flutter test -r expanded --concurrency=1 --timeout=2x
      - name: Generate coverage report
        run: flutter test --coverage -r expanded --concurrency=1 --timeout=2x
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/lcov.info
          retention-days: 30

  coverage-gate:
    runs-on: ubuntu-latest
    needs: widget-tests
    continue-on-error: true  # v1-rc.1: Allow deployment with <40% coverage
    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: coverage/
      - name: Check coverage threshold (>= 40%)
        run: |
          COVERAGE=$(awk 'BEGIN{lc=0;lt=0} /^DA:/{split($0,a,":"); split(a[2],b,","); lt++; if(b[2]>0) lc++} END{if(lt==0){print 0}else{print lc/lt*100}}' coverage/lcov.info)
          echo "COVERAGE=${COVERAGE}%"
          if (( $(echo "$COVERAGE < 40.0" | bc -l) )); then
            echo "::warning::Coverage ${COVERAGE}% is below 40% threshold (v1-rc.1: non-blocking)"
            exit 1
          fi
          # TODO Stage 2: Increase threshold to 60%

  integration-tests:
    runs-on: ubuntu-latest
    continue-on-error: true  # Non-blocking for Stage 0; will fix in Stage 1
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Install Firebase CLI
        run: curl -sL https://firebase.tools | bash
      - run: flutter pub get
      - name: Run integration tests on emulators
        run: |
          firebase emulators:exec --only firestore,functions,auth,storage -- \
            flutter test integration_test -r expanded --concurrency=1 --timeout=3x \
            --dart-define=USE_EMULATORS=true

  rules-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Install functions dependencies
        run: npm --prefix functions install
      - name: Run Firestore rules tests
        run: |
          firebase emulators:exec --only firestore -- \
            npm --prefix functions test -- --testPathPattern=rules.test.ts
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
      - name: Run Storage rules tests
        run: |
          firebase emulators:exec --only storage,firestore -- \
            npm --prefix functions test -- --testPathPattern=storage-rules.test.ts
        env:
          FIREBASE_STORAGE_EMULATOR_HOST: localhost:9199
          FIRESTORE_EMULATOR_HOST: localhost:8080
      - name: Run setUserRole integration tests
        run: |
          firebase emulators:exec --only firestore,auth -- \
            npm --prefix functions test -- --testPathPattern=setUserRole.integration.test.ts
        env:
          FIRESTORE_EMULATOR_HOST: localhost:8080
          FIREBASE_AUTH_EMULATOR_HOST: localhost:9099
