name: Updates Governance
on:
  pull_request:
  push:
    branches: [ main, develop, chore/*, fix/* ]
  schedule:
    - cron: '0 10 * * 1' # Mondays 10:00 UTC
  workflow_dispatch:
jobs:
  validate-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Shellcheck validator
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning
      - name: Run governance validation
        run: |
          chmod +x scripts/validate_updates.sh
          ./scripts/validate_updates.sh
      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: update-reports
          path: .reports
  dependency-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '20'
      - name: Audit npm projects
        run: |
          set -e
          for d in functions firestore-tests; do
            if [ -f "$d/package.json" ]; then
              (cd "$d" && npm ci && npm audit --audit-level=high --omit=dev) || exit 1
            fi
          done
  version-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Pub outdated (non-failing)
        run: flutter pub outdated || true
